modLoader="${mod_loader}"
loaderVersion="${loader_version}"
license="${mod_license}"
issueTrackerURL="${mod_issueTrackerURL}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/multihitboxlib"
logoFile="logo.png"
credits="${mod_credits}"
description='''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"

# Base
[[dependencies."${modid}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="minecraft"
    type="required"
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"

# Dependencies (Optional)
#   COMMON
[[dependencies."${modid}"]]
    modId="geckolib"
    type="optional"
    versionRange="${geckolib_version_range}"
    ordering="BEFORE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="azurelib"
    type="optional"
    versionRange="${azurelib_version_range}"
    ordering="BEFORE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="jei"
    type="optional"
    versionRange="${jei_version_range}"
    ordering="BEFORE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="jeed"
    type="optional"
    versionRange="${jeed_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="jade"
    type="optional"
    versionRange="${jade_version_range}"
    ordering="NONE"
    side="BOTH"

#   CLIENT
[[dependencies."${modid}"]]
    modId="appleskin"
    type="optional"
    versionRange="${appleskin_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies."${modid}"]]
    modId="catalogue"
    type="optional"
    versionRange="${catalogue_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies."${modid}"]]
    modId="gamemenumodoption"
    mandatory=false
    versionRange="${gmmo_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies."${modid}"]]
    modId="mixinbooster"
    mandatory=true
    versionRange="${mixinbooster_version_range}"
    ordering="BEFORE"
    side="BOTH"
